coins = ['BTC', 'TEN', 'AAVE', 'ABYSS', 'ACT', 'ADA', 'ALGO', 'AOA', 'ATOM', 'ATT', 'BAL', 'BAT', 'BCD', 'BCH', 'BCHA',
         'BSV', 'BNB', 'BTG', 'BTS', 'BTT', 'CEL',
         'CELO', 'CKB', 'COAL', 'COTI', 'COMP', 'CRO', 'DAD', 'DAI', 'DASH', 'DAX', 'DEP', 'DGB', 'DGX', 'DOGE', 'DOT',
         'EGLD', 'EM', 'EOS', 'ETC', 'ETH', 'EURS',
         'FIL', 'FIRO', 'GRT', 'GSC', 'GXC', 'HEDG', 'HIVE', 'HNST', 'HPB', 'IDK', 'IGNIS', 'IOST', 'IOTA', 'JST',
         'KDAG', 'LET', 'LGOLD', 'LINK', 'LTC',
         'LYFE', 'MANA', 'MATIC', 'MBL', 'MKR', 'NEO', 'NRG', 'NXT', 'OCEAN', 'OCTO', 'OKB', 'OMG', 'ONT', 'OXT',
         'PAXG', 'QTUM', 'REN', 'REPV2', 'RVN', 'SFI',
         'SNX', 'SUMO', 'SUSHI', 'TFUEL', 'THETA', 'TITAN', 'TRX', 'UMA', 'UNI', 'USDT', 'VEX', 'VIDY', 'VIDYX', 'VSYS',
         'WAVES', 'WBTC', 'WNXM', 'WOZX',
         'XLM', 'XEM', 'XDC', 'XMR', 'XRP', 'XTZ', 'YFI', 'YFII', 'ZEC', 'ZIL', 'ZRX']
